Fix count for route of Private IPV6 egress
When having the variable `enable_ipv6` set to `true`(as in https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/examples/simple-vpc)
when trying to destroying a newly created VPC the following errors is
outputted
```
Error: Error deleting route: InvalidRoute.NotFound: no route with destination-cidr-block ::/0 in route table
```

As this resource uses the `aws_route_table.private.*.id` and needs to be
one per each `aws_route_table.private.*.id` entry this change does exactly
this.

Issue Reference https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/373
Proposed solution on similar issue:
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/373#issuecomment-583743673